version: '3.7'

services:
  wmi-exporter:
    image: ${IMAGE_NAME:-registry.gitlab.com/cabildo-tf/vente/deploy/ansible-playbook/master}:${IMAGE_TAG:-latest}
    environment:
      TAG_HOSTS:
      HOSTS:
      ANSIBLE_USER:
      ANSIBLE_PASSWORD:
      ANSIBLE_CONNECTION:
      ANSIBLE_WINRM_SERVER_CERT_VALIDATION:
      ANSIBLE_PORT:
      ANSIBLE_WINRM_MESSAGE_ENCRYPTION:
      ANSIBLE_WINRM_TRANSPORT:
    configs:
      - source: install-wmi-exporter-config
        target: /playbook/install_wmi_exporter.yml
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '0.1'
          memory: 10M
        reservations:
          memory: 5M

configs:
  install-wmi-exporter-config:
    name: ${INSTALL_WMI_EXPORTER_CONFIG_NAME:-install-wmi-exporter}
    file: ./playbook/install_wmi_exporter.yml